"""Add Provenance Layer

Revision ID: 897a7246ee6f
Revises: d4c9e4c63819
Create Date: 2026-08-17 23:06:38.512935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '897a7246ee6f'
down_revision: Union[str, None] = 'd4c9e4c63819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_provenances',
    sa.Column('memory_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('original_content_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_provenances_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_provenances'))
    )
    op.create_index(op.f('ix_memory_provenances_memory_id'), 'memory_provenances', ['memory_id'], unique=True)
    op.add_column('memories', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('memory_versions', sa.Column('content_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_versions', 'content_hash')
    op.drop_column('memories', 'version')
    op.drop_index(op.f('ix_memory_provenances_memory_id'), table_name='memory_provenances')
    op.drop_table('memory_provenances')
    # ### end Alembic commands ###
